### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by grizeldi** [grekiki/GravityRow#2]
This is not even remotely standard java code style. Class names starting with non capital letter? Like come on!
And that's not even the only example.

**Comment by grekiki** [comment]
Well I never learnt the style... I just decided to try and program something that is not a simple 100 line algorithm. That I put it on github was mostly to learn how to use it, and what it can do. I program mostly in contests so I don't have any idea of what I should abide by with "working" code.

**Comment by grekiki** [comment]
Let's close the project.
